### ISSUE TITLE
TODO found scheduler.py

### ISSUE THREAD

**Issue by ghost** [general-ai-challenge/Round1#11] opened 2017-04-16 17:43 UTC
TODO found in src/core/scheduler.py

Line 83 #TODO: Create a BatchedScheduler that takes as an argument anotherelow

(corrected, paste error)

**Comment by MLanghof** [comment] 2017-04-16 23:49
> Line 83 #TODO: Create a BatchedScheduler that takes as an argument anothe

Carried over from the original repo.

> Line 143 # TODO: decide what to do here.

Doesn't actually exist. Copy paste from #10 I suppose.

**Comment by ghost** [comment] 2017-04-17 10:15
"Carried over from the original repo.", which is a beta release. I don't want to add to the overhead reviewing issues here if they are intended features. Will post to upstream where applicable.

I did not file issues for all of the existing FIXME's. TODO's, XXX's. etc in this repository, The issues posted are just the first six on the list.

**Comment by martinpoliak-goodai** [comment] 2017-04-18 10:26
Thanks for the code quality review, Stephen. When we were releasing the modified CommAI environment for the challenge, we had a long discussion whether to keep the original CommAI code or whether to strip the environment to the minimum version that still runs. Eventually we chose the first option - keep the original CommAI code, to make it easier for anyone to have a look on the original environment or switch to it if desired. This also means that we carried over issues from the original repo (like some of those TODOs and FIXMEs you report), which however have little or no relation to the actual challenge. Please be considerate of this when opening new code quality-related issues and check the original repo to find where they appear first.

**Comment by ghost** [comment] 2017-04-18 11:10
Sorry if I gave the impression the issue reports I posted were thought of as a 'code review', I am just beginning the task, they are the the first of 352 potential issues based on a static review https://codeclimate.com/github/stephenbhope/Round1-shope-DEV an do not include the Round1 structural issues, repository instructions,  installer, Python 3.5 port for native byte code handling in place of the back ports for Python 2.x., and bringing the GoodAI-env out of it's current beta status.

If you will please note, this is not a code review or a pull request, you have made it very clear in your comments to me you do not wish to receive contributions. 

If you not wish to receive bug or issue reports for general-ai-challenge/Round1, please update your contributor information.  

The issues reported on the Round1 forum hosted by the challenge by another prospective entrant, have not been addressed..  What if any mechanism should be used to report bugs or issues?

**Comment by martinpoliak-goodai** [comment] 2017-04-18 11:21
Hi Stephen, please let me be clear on this - we are happy for contributions and if you look at the history of the repository, you will notice that we accepted and merged a number of them so far. 
I rejected your first pull request because, as I explained already, it was inconsistent with other files in the repository. Since the challenge participants are already using the code, we need to keep the changes to the repository small or at least self-contained - we do not want to force the participants into checking 50 individual commits over the course of several weeks for finding out whether something relevant has changed. Therefore if we merge code quality improvements, it will be done in a single pull request so as not to confuse the participants about the content of the changes.
We are trying to address all issues that appear here and on the challenge forum. Can you please send me a link to the issue you feel got omitted on the forum? 
Thanks for your help,
Martin

**Comment by ghost** [comment] 2017-04-18 11:26
I believe you misunderstand the mechanics and purpose for creating a fork as the first step of Round1.

**Comment by ghost** [comment] 2017-04-18 16:11
As Daria and I seem to have concluded our discussion about my potential 
involvement with the General AI Challenge not being needed at this time, 
I will not be directly participating in the 
https://github.com/general-ai-challenge/Round1 fork.

I would respectfully suggest, you read the Round1 related posts on the 
General AI Challenge Forum at: 
https://discourse.general-ai-challenge.org/ for further details. There 
only a handful of posts total, from people outside of GoodAI.

Raising an issue on a public Github repository is not an indication I 
would like enter into a discussion of your internal organisational 
management here, as I do not feel this is an appropriate channel.

**Comment by krisives** [comment] 2017-04-18 20:41
This is a lot over a leftover `TODO` that realistically only CommonAI should change, What's wrong with reporting the issues in their repository?

**Comment by martinpoliak-goodai** [comment] 2017-04-20 08:06
Closing as duplicate of the "umbrella" code quality issue https://github.com/general-ai-challenge/Round1/issues/16

**Closed as completed by martinpoliak-goodai** 2017-04-20 08:06 UTC
Labels: duplicate
