### ISSUE TITLE
TODO found environment.py (2)

### ISSUE THREAD

**Issue by ghost** [general-ai-challenge/Round1#10] opened 2017-04-16 17:39 UTC
TODO Found in src/core/environment.py 

Line 120   # TODO this bit is dropped otherwise on a timeout...

Line 143  # TODO: decide what to do here.

**Comment by martinpoliak-goodai** [comment] 2017-04-20 08:06
Closing as duplicate of the "umbrella" code quality issue https://github.com/general-ai-challenge/Round1/issues/16

**Closed as completed by martinpoliak-goodai** 2017-04-20 08:06 UTC
Labels: duplicate
