### ISSUE TITLE
FIXME found repetition.py

### ISSUE THREAD

**Issue by ghost** [general-ai-challenge/Round1#13] opened 2017-04-16 17:50 UTC
FIXME found in src/tasks/competition/repetition.py 

Line 25 # FIXME: replace with association's objects and properties?

**Comment by martinpoliak-goodai** [comment] 2017-04-18 10:15
Thanks for the issue, please move upstream (to the original CommAiEnv repo).

**Comment by ghost** [comment] 2017-04-18 11:24
I am not a project maintainer for general-ai-challenge/Round1 and we are the only two participants in this issue, it reads like an instruction to this repository's team, so I am unsure who you are addressing.

**Comment by martinpoliak-goodai** [comment] 2017-04-20 08:06
Closing as duplicate of the "umbrella" code quality issue https://github.com/general-ai-challenge/Round1/issues/16

**Closed as completed by martinpoliak-goodai** 2017-04-20 08:06 UTC
Labels: duplicate
