### ISSUE TITLE
FIXME found __inti__.py

### ISSUE THREAD

**Issue by ghost** [general-ai-challenge/Round1#12] opened 2017-04-16 17:47 UTC
FIXME found  src/learners/__init__.py

Line 10 # FIXME: this architecture is probably fragile. Test where it fails and fix it.

**Comment by martinpoliak-goodai** [comment] 2017-04-18 10:15
Please move upstream.

**Comment by ghost** [comment] 2017-04-18 11:24
I am not a project maintainer for general-ai-challenge/Round1 and we are the only two participants in this issue, it reads like an instruction to this repository's team, so I am unsure who you are addressing.

**Comment by krisives** [comment] 2017-04-18 20:14
@stephenbhope I think it's on you to report this upstream to https://github.com/facebookresearch/CommAI-env

Thanks for helping with the project

**Comment by ghost** [comment] 2017-04-18 22:25
I was reporting an issue with this repository, to this repository. I understand your organisation has a very different view on responsibilities than I do. I have repeatedly indicated I am not attempting to start a debate with your practices, and have repeatedly stated I will cease reporting issues to this repository.

I am not an employee of GoodAI or Facebook, and have a different idea of what my responsibilities are.

Thank you for your opinion, unless you are seeking clarification of the issue report, I will not be responding further.

**Comment by martinpoliak-goodai** [comment] 2017-04-20 08:06
Closing as duplicate of the "umbrella" code quality issue https://github.com/general-ai-challenge/Round1/issues/16

**Closed as completed by martinpoliak-goodai** 2017-04-20 08:06 UTC
Labels: duplicate
